# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/devin/Workspaces/VivadoWorkspace/spi_register_bank/spi_register_bank.srcs/sources_1/ip/string_module_blk_mem/string_module_blk_mem.xci
# IP: The module: 'string_module_blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/Workspaces/VivadoWorkspace/spi_register_bank/spi_register_bank.srcs/sources_1/ip/string_module_blk_mem/string_module_blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'string_module_blk_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/devin/Workspaces/VivadoWorkspace/spi_register_bank/spi_register_bank.srcs/sources_1/ip/string_module_blk_mem/string_module_blk_mem.xci
# IP: The module: 'string_module_blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/Workspaces/VivadoWorkspace/spi_register_bank/spi_register_bank.srcs/sources_1/ip/string_module_blk_mem/string_module_blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'string_module_blk_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
